import{Canvas,useFrame,useThree}from'@react-three/fiber';import{Cloud,Float,Sparkles,Stars}from'@react-three/drei';import{Suspense,useRef}from'react';import*as THREE from'three';import type{Quality}from'../../hooks/useDeviceQuality';import{PokemonPopulation}from'./PokemonPopulation';
type Props={quality:Quality;night:boolean;reduced:boolean;entered:boolean;onSecret:()=>void};
function Tree({p,s=1}:{p:[number,number,number];s?:number}){const crown=useRef<THREE.Group>(null);useFrame(({clock})=>{if(crown.current)crown.current.rotation.z=Math.sin(clock.elapsedTime+p[0])*.025});return <group position={p} scale={s}><mesh position-y={.65} castShadow><cylinderGeometry args={[.15,.24,1.3,7]}/><meshStandardMaterial color="#70452b"/></mesh><group ref={crown} position-y={1.45}><mesh castShadow><dodecahedronGeometry args={[.72,0]}/><meshStandardMaterial color="#318d55" flatShading/></mesh><mesh position={[.35,.15,.1]}><dodecahedronGeometry args={[.46,0]}/><meshStandardMaterial color="#52b96e" flatShading/></mesh></group></group>}
function Avatar(){const r=useRef<THREE.Group>(null);useFrame(({clock})=>{if(r.current)r.current.rotation.y=Math.sin(clock.elapsedTime*.55)*.12});return <group ref={r} position={[0,.58,1]}><mesh castShadow position-y={.75}><capsuleGeometry args={[.28,.72,6,10]}/><meshStandardMaterial color="#1649a0"/></mesh><mesh castShadow position-y={1.55}><sphereGeometry args={[.32,16,12]}/><meshStandardMaterial color="#dca679"/></mesh><mesh position={[0,1.76,0]}><sphereGeometry args={[.34,12,8,0,Math.PI*2,0,1.7]}/><meshStandardMaterial color="#172138"/></mesh><mesh position={[.34,.83,-.02]} rotation-z={-.18}><boxGeometry args={[.08,.65,.45]}/><meshStandardMaterial color="#f4c430"/></mesh><mesh position={[0,.82,.3]} rotation-x={-.25}><boxGeometry args={[.62,.05,.42]}/><meshStandardMaterial color="#d9e6f4" metalness={.35}/></mesh></group>}
function House({p}:{p:[number,number,number]}){return <group position={p}><mesh castShadow position-y={.55}><boxGeometry args={[1.4,1.1,1.15]}/><meshStandardMaterial color="#f4ead7"/></mesh><mesh castShadow position-y={1.35} rotation-y={Math.PI/4}><coneGeometry args={[1.05,.8,4]}/><meshStandardMaterial color="#df4d43"/></mesh><mesh position={[0,.45,.59]}><boxGeometry args={[.35,.7,.04]}/><meshStandardMaterial color="#224d7a"/></mesh></group>}
function Terrain({quality,onSecret}:{quality:Quality;onSecret:()=>void}){const trees=quality==='low'?[[4,0,-1],[-4,0,-3],[-3,0,3]]:[[4,0,-1],[-4,0,-3],[-3,0,3],[3,0,4],[6,0,3],[-6,0,1],[2,0,-5]];return <><mesh rotation-x={-Math.PI/2} receiveShadow><circleGeometry args={[13,48]}/><meshStandardMaterial color="#63b667" roughness={1}/></mesh><mesh position={[0,.025,-.3]} rotation-x={-Math.PI/2}><planeGeometry args={[2.1,18]}/><meshStandardMaterial color="#dac68e"/></mesh><mesh position={[8,-.02,0]} rotation-x={-Math.PI/2}><circleGeometry args={[5,36]}/><meshStandardMaterial color="#45aee3" transparent opacity={.85} roughness={.25}/></mesh>{trees.map((p,i)=><Tree key={i} p={p as [number,number,number]} s={.8+(i%3)*.14}/>)}<House p={[-2.6,0,-1.3]}/><House p={[3.1,0,-3.2]}/><Avatar/>{quality!=='low'&&<></>}{quality==="high"&&<></>}<PokemonPopulation quality={quality}/><group position={[-5.2,.4,3.8]} onClick={onSecret}><mesh><sphereGeometry args={[.24,16,12,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color="#ef3e43"/></mesh><mesh rotation-x={Math.PI}><sphereGeometry args={[.24,16,12,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color="white"/></mesh><mesh position-z={.23}><sphereGeometry args={[.07,12,8]}/><meshStandardMaterial color="white"/></mesh></group></>}
function Mountains(){return <group position={[0,-.2,-10]}>{[-7,-3,1,5,9].map((x,i)=><mesh key={x} position={[x,1,-i%2]} rotation-y={.2}><coneGeometry args={[3.2,5.5,5]}/><meshStandardMaterial color={i%2?'#4c78a4':'#3d668e'} flatShading/></mesh>)}</group>}
function Camera({reduced,entered}:{reduced:boolean;entered:boolean}){const{camera,mouse}=useThree();useFrame(()=>{const scroll=scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight);const target=entered?new THREE.Vector3(reduced?0:mouse.x*.9,5.4-scroll*1.1,9.4-scroll*1.8):new THREE.Vector3(0,10.5,22);camera.position.lerp(target,.025);camera.lookAt(0,.7,-.5)});return null}
function Scene({quality,night,reduced,entered,onSecret}:Props){return <><color attach="background" args={[night?'#06132d':'#8ed6f4']}/><fog attach="fog" args={[night?'#06132d':'#bfe7f3',12,28]}/><ambientLight intensity={night?.42:1.1}/><hemisphereLight args={[night?'#5b75c8':'#d7f4ff','#29633b',night?.5:1.4]}/><directionalLight position={[6,10,5]} intensity={night?.65:2.1} castShadow={quality==='high'} shadow-mapSize={[1024,1024]}/>{night&&<Stars radius={40} depth={18} count={quality==='low'?250:700} factor={2}/>}<Mountains/><Terrain quality={quality} onSecret={onSecret}/>{quality!=='low'&&<Float speed={.35} floatIntensity={.3}><Cloud position={[-5,7,-10]} scale={1.3} opacity={.6}/><Cloud position={[6,6,-8]} scale={.9} opacity={.5}/></Float>}<Sparkles count={quality==="low"?20:quality==="medium"?65:140} scale={[18,8,18]} size={quality==="high"?2:1} speed={.25}/><Camera reduced={reduced} entered={entered}/></>}
export default function World(props:Props){return <Canvas shadows={props.quality==='high'} dpr={props.quality==='low'?1:[1,1.5]} camera={{position:[0,5.4,9.4],fov:48}} gl={{antialias:props.quality!=='low',powerPreference:'high-performance'}}><Suspense fallback={null}><Scene {...props}/></Suspense></Canvas>}
